idea:
    build: .
    labels:
        org.kurron.description: "JetBrains MPS DSL IDE"
        org.kurron.version: "3.2.3"
    container_name: "mps"
    net: "host"
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/vagrant:/home/developer
    environment:
        DISPLAY: unix:0.0
    user: 1000:1000
